import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    height: 400,
    backgroundColor: "#C4C4C4",
    overflow: "scroll",
  },
  searchBar: {
    // flex: 1,
    flexDirection: "row",
    marginTop: 120,
    justifyContent: "center",
    alignItems: "center",
  },
  recarregar: {
    top: 90,
    left: 200,
    right: 0,
    // width: 30,
    backgroundColor: "#575757",
    padding: 5,
    borderRadius: 20,
    shadowColor: "#000000",
    elevation: 10,
  },
  topo: {
    // flex: 1,
    flexDirection: "row",
  },
  lista: {
    top: 50,
    // height: 10,
    maxHeight: 350,
  },
  textButtonTitle: {
    color: "#000",
    fontWeight: "bold",
  },
  texto: {
    color: "#fff",
    fontWeight: "bold",
  },
  texto2: {
    left: 30,
    top: 30,
    color: "#000",
    fontSize: 20,
    fontWeight: "bold",
  },
  titleCriar: {
    top: 60,
    left: 10,
    width: 90,
    backgroundColor: "#FFFFFF",
    padding: 10,
    borderRadius: 20,
    shadowColor: "#000000",
    elevation: 10,
  },
  item: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#575757",
    maxHeight: 60,
    alignItems: "center",
    padding: 15,
    margin: 10,
    borderRadius: 10,
  },
  icons: {
    flexDirection: "row",
  },
  add: {
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#575757",
    margin: 10,
    borderRadius: 100,
  },
  posicao: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  registrar: {
    flexDirection: "row",
    justifyContent: "center",
    top: 30,
    margin: 5,
  },
  bordaTexto: {
    backgroundColor: "#575757",
    alignContent: "center",
    padding: 10,
    borderRadius: 100,
    margin: 5,
  },
});
